### ISSUE TITLE
添加到win的计划任务，无法不登录自启动

### ISSUE THREAD

**Issue by tsarwade** [ZingerLittleBee/serverbee-desktop#6]
添加到win的计划任务，无法不登录自启动，主程序无法启动，只有双击快捷方式才能正常启动

**Comment by ZingerLittleBee** [comment]
界面程序无法在不登录的情况下启动

可以下载 [`serverbee-web`](https://github.com/ZingerLittleBee/server_bee-backend/releases) 模块，
并且进行如下步骤

1. 打开 Windows 管理工具- 任务计划程序
2. 右键点击**任务计划程序库**-**创建任务**
3. 具体设置如下图

<img width="599" alt="image" src="https://user-images.githubusercontent.com/33377263/231097917-a0170041-aaef-4c28-a49f-9cbfd426a123.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/33377263/231098411-39f7c71f-7617-464b-9eef-21bdcbadbca0.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/33377263/231099375-b44f6e0a-a2a3-4e7e-b967-60a0e92cd02f.png">
